CREATE TABLE IF NOT EXISTS plants (
  id SERIAL PRIMARY KEY,
  bot_name VARCHAR(255),
  com_name VARCHAR(255),
  exposure VARCHAR(255),
  climate_zone VARCHAR(255)
);

INSERT INTO plants (bot_name, com_name, exposure, climate_zone) 
VALUES ('Acer negundo', 'Box Elder', 'Full sun, partial sun', '2-10'),
('Acer rubrum', 'Red Maple', 'Full sun, partial sun', '3-9'),
('Acer saccharum', 'Sugar Maple', 'Full sun, partial sun', '3-9'),
('Achillea millefolium', 'White Yarrow', 'Full sun, partial sun', '3-9'),
('Actaea pachypoda', 'White Baneberry', 'Partial sun, shade', '3-9'),
('Actaea racemosa', 'Black Cohosh', 'Partial sun, shade', '3-8'),
('Adiantum capillus-veneris', 'Southern Maidenhair Fern', 'Partial sun, shade', '8-11'),
('Adiantum pedatum', 'Northern Maidenhair Fern', 'Partial sun, shade', '3-8'),
('Aesculus flava', 'Yellow Buckeye', 'Full sun, partial sun', '3-8'),
('Aesculus glabra', 'Ohio Buckeye', 'Full sun, partial sun', '3-7'),
('Aesculus pavia', 'Red Buckeye', 'Full sun, partial sun', '5-9'),
('Agalinis purpurea', 'Purple False Foxglove', 'Full sun, partial sun', '3-11'),
('Agastache foeniculum', 'Anise Hyssop', 'Full sun, partial sun', '4-8'),
('Agastache nepetoides', 'Yellow Giant Hyssop', 'Full sun', '2-8'),
('Ageratina altissima', 'White Snakeroot', 'Partial sun', '3-8'),
('Allium cernuum', 'Ladys Leek', 'Full sun, partial sun', '3-9'),
('Alnus serrulata', 'Smooth Alder', 'Full sun, partial sun', '4-9'),
('Amelanchier arborea', 'Downy Serviceberry', 'Full sun, partial sun', '4-9'),
('Amelanchier laevis', 'Allegheny Serviceberry', 'Full sun, partial sun', '4-8'),
('Amelanchier stolonifera', 'Running Serviceberry', 'Full sun, partial sun', '4-8'),
('Amorpha fruticosa', 'Indigo Bush', 'Full sun', '4-9'),
('Amsonia tabernaemontana', 'Blue Star', 'Full sun, partial sun', '3-9'),
('Amsonia tabernaemontana var. salicifolia', 'Eastern Blue Star', 'Full sun, partial sun', '3-9'),
('Andropogon gerardii', 'Big Bluestem', 'Full sun', '4-9'),
('Andropogon glomeratus', 'Bushy Bluestem', 'Full sun', '5-9'),
('Andropogon ternarius', 'Splitbeard Bluestem', 'Full sun, partial sun', '6-10'),
('Andropogon virginicus', 'Broom Sedge', 'Full sun', '5-10'),
('Anemone canadensis', 'Meadow Anemone', 'Partial sun, shade', '3-8'),
('Anemone quinquefolia', 'Wood Anemone', 'Partial sun, shade', '5-8'),
('Anemone virginiana', 'Thimbleweed', 'Full sun, partial sun', '2-8'),
('Angelica atropurpurea', 'American Angelica', 'Full sun, partial sun', '4-7'),
('Antennaria neglecta', 'Field Pussytoes', 'Full sun, partial sun', '3-8'),
('Antennaria plantaginifolia', 'Pussytoes', 'Full sun, partial sun', '3-8'),
('Apios americana', 'American Groundnut', 'Full sun, partial sun', '4-9');